name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      run: docker build -t my-app .
      
    - name: Run the Docker container
      run: docker run --rm my-app python3 newtest.py
